apiVersion: v1
kind: Namespace
metadata:
  name: churchball

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: churchball-skvnent-com
  namespace: churchball
spec:
  secretName: churchball-skvnent-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "churchball.skvnent.com"
  dnsNames:
  - "churchball.skvnent.com"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churchball-nginx-conf-pvc
  namespace: churchball
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churchball-db-pvc
  namespace: churchball
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churchball
  namespace: churchball
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churchball
  template:
    metadata:
      labels:
        app: churchball
    spec:
      containers:
      - name: churchball
        image: harbor.skvnent.com/churchball/churchball-python:0.14
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: churchball-db-config
            mountPath: /app/db
        env:
        - name: TZ
          value: America/Denver
      - name: nginx
        image: nginx@sha256:7ba6006df2033690d8c64bd8df69e4a1957b78e57b4e32141c78d72a5e0de63d
        ports:
        - containerPort: 80
        volumeMounts:
          - name: churchball-nginx-config
            mountPath: /etc/nginx/conf.d
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo 'server {
              listen 80;
              server_name _;
              location / {
                proxy_set_header Host $host ;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto: http;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_pass http://churchball:5000;
                proxy_read_timeout 10;
              }
            }' > /etc/nginx/conf.d/default.conf;
            nginx -g 'daemon off;'
        env:
        - name: FLASK_APP
          value: churchball
        - name: FLASK_ENV
          value: development
        - name: TZ
          value: America/Denver
      volumes:
        - name: churchball-nginx-config
          persistentVolumeClaim:
            claimName: churchball-nginx-conf-pvc
        - name: churchball-db-config
          persistentVolumeClaim:
            claimName: churchball-db-pvc
          
---
apiVersion: v1
kind: Service
metadata:
  name: churchball
  namespace: churchball
spec:
  selector:
    app: churchball
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: churchball
spec:
  selector:
    app: churchball
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: churchball-ingress
  namespace: churchball
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`churchball.skvnent.com`)
      kind: Rule
      services:
        - name: nginx
          port: 80
  tls:
    secretName: churchball-skvnent-com-tls 
          