---
apiVersion: v1
kind: Namespace
metadata:
  name: churchball

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churchball-nginx-conf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi
---

---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churchball
  namespace: churchball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: churchball
  template:
    metadata:
      labels:
        app: churchball
    spec:
      containers:
      - name: churchball
        image: harbor.skvnent.duckdns.org/churchball/churchball-python:0.1
        ports:
        - containerPort: 5000
      - name: nginx
        image: harbor.skvnent.duckdns.org/churchball/churchball-nginx:0.1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: churchball-nginx-config
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: churchball-nginx-config
          persistentVolumeClaim:
            claimName: churchball-nginx-conf-pvc

---   
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: churchball
    namespace: churchball
  data:
    FLASK_PORT: "5000"
    FLASK_DEBUG: "0"
  
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx
    namespace: default
  data:
    default.conf: |
      server {
          listen 80;

          server_name _;

          location / {
              proxy_set_header Host $host ;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-Proto: http;

              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";

              proxy_pass http://churchball:5000;
              proxy_read_timeout 10;
          }
      }

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: churchball-ingress
  namespace: churchball
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`churchball.skvnent.duckdns.org`)
      kind: Rule
      services:
        - name: churchball
          port: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: churchball
  namespace: churchball
spec:
  selector:
    app: churchball
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80