apiVersion: v1
kind: Namespace
metadata:
  name: churchball

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churchball-nginx-conf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churchball
  namespace: churchball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: churchball
  template:
    metadata:
      labels:
        app: churchball
    spec:
      containers:
      - name: churchball
        image: harbor.skvnent.duckdns.org/churchball/churchball-python:0.2
        ports:
        - containerPort: 5000
      - name: nginx
        image: harbor.skvnent.duckdns.org/churchball/churchball-nginx:0.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: churchball-nginx-config
            mountPath: /etc/nginx/conf.d
        env:
        - name: FLASK_APP
          value: churchball
        - name: FLASK_ENV
          value: development
      volumes:
        - name: churchball-nginx-config
          persistentVolumeClaim:
            claimName: churchball-nginx-conf-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: churchball
  namespace: churchball
spec:
  selector:
    app: churchball
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: churchball
spec:
  selector:
    app: churchball
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: churchball-ingress
  namespace: churchball
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`churchball.skvnent.duckdns.org`)
      kind: Rule
      services:
        - name: nginx
          port: 80
          