version: '3.8'
services:
  python:
    container_name: churchball-python
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: churchball-nginx
    restart: always
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - python
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 