version: '3.8'
services:
  python:
    container_name: churchball
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./db:/app/db
    networks:
      - db_network
      - web_network
  nginx:
    image: nginx@sha256:0f859db466fda2c52f62b48d0602fb26867d98edbd62c26ae21414b3dea8d8f4
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - python
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 